import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Next13NProgress, Link } from "nextjs13-progress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen flex flex-col">
          <header className="flex items-center gap-6 justify-center text-2xl text-white bg-slate-800 py-4">
            <Link href="/">Home</Link>
            <Link href="/page2">Page2</Link>
            <Link href="/slow-page">Slow Page</Link>
          </header>
          {children}
        </main>
        <Next13NProgress color="red" height={5} />
      </body>
    </html>
  );
}
